swagger: "2.0"
info:
  version: "1.0.0"
  title: "URL Shortener"

host: "localhost"
schemes:
  - "http"
paths:
  /url:
    post:
      tags:
        - "url"
      summary: "add new url"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/UrlBody"
      responses:
        "200":
          description: "Short url is created"
          schema:
            $ref: "#/definitions/UrlResponse"
        "422":
          description: "Validation error"
  /url/{id}:
    put:
      tags:
        - "url"
      summary: "Update an existing url"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: path
          required: true
          name: "id"
          type: integer
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/EditUrlBody"
      responses:
        "200":
          description: "Short url is edited"
          schema:
            $ref: "#/definitions/UrlResponse"
        "422":
          description: "Validation error"
definitions:
  EditUrlBody:
    type: "object"
    required:
      - "code"
    properties:
      code:
        type: "string"
        example: "string"
  UrlBody:
    type: "object"
    required:
      - "url"
    properties:
      url:
        type: "string"
        example: "http://example.com"
  UrlResponse:
    type: "object"
    properties:
      shortLink:
        type: "string"
        example: "http://localhost/f141f"
      urlId:
        type: "integer"
        example: 10
